from setuptools import setup, find_packages

setup(
    name="planner",
    version="1.0",
    url='http://github.com/slspeek/gnudok-planner/',
    license='GPL',
    description="Planner for Juttersdok",
    author='Steven Speek',
    packages=find_packages('src'),
    package_dir={'': 'src'},
    install_requires=['setuptools',
                      'factory_boy',
                      'docutils',
                      'flup==1.0.2',
                      'django',
                      'django-bootstrap-toolkit',
                      'django-extensions',
                      'django-factory_boy',
                      'django_jenkins',
                      'django-nose',
                      'django-webtest',
                      'psycopg2',
                      'WebTest',
                      'selenium',
                      'MySQL-python'],
)
